# Generated by Django 4.2.27 on 2026-01-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_carimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
