# Generated by Django 4.2.27 on 2026-02-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_booking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_code',
        ),
    ]
